#define TAPPING_TERM 165
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define ACHORDION_STREAK
#define QUICK_TAP_TERM 90

#define COMBO_TERM 40
#define COMBO_VARIABLE_LEN

// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
