#define COMBO_TERM 40
#define TAPPING_TERM 165
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 80
#define PERMISSIVE_HOLD_PER_KEY
#define BILATERAL_COMBINATIONS 300
#define COMBO_VARIABLE_LEN
// #define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
